package com.tdebug.criminalintent;

import android.content.Context;

import java.util.ArrayList;
import java.util.UUID;

/**
 * Created by tdebug on 03/12/14.
 */
public class CrimeLab {
//    private static CrimeLab ourInstance = new CrimeLab();  generated by adnr studio

    ArrayList<Crime> mCrimes;

    private static CrimeLab sCrimeLab;
    private Context mAppContext;

/*    public static CrimeLab getInstance() {        //generated by studio
        return ourInstance;
    }*/

    public void addCrime(Crime c)
    {
        mCrimes.add(c);
    }

    private CrimeLab(Context appContext) {
        mAppContext = appContext;
        mCrimes = new ArrayList<Crime>();

// crimes auto generation
/*        for (int i = 0; i < 100; i++) {
            Crime c = new Crime();
            c.setTitle("Crime #" + i);
            c.setSolved(i % 2 == 0);
            mCrimes.add(c);
        }*/
    }

    public static CrimeLab get(Context c) {
        if (sCrimeLab == null) {
            sCrimeLab = new CrimeLab(c.getApplicationContext());
        }
        return sCrimeLab;

    }

    public ArrayList<Crime> getCrimes() {
        return mCrimes;
    }

    public Crime getCrime(UUID id)
    {
        for (Crime c : mCrimes)
        {
            if (c.getId().equals(id))
                return c;
        }
        return null;

    }

}
